# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update Index JSON

on:
  schedule:
  - cron: "5 16 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_ACCESS_TOKEN }}
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx
    - name: Run python app
      run: |
        python index.py
    - name: Push to github
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add index.json
        git commit -m "Update index JSON file"
        git push
